### PR TITLE
Version updates

### PR DESCRIPTION
**Pull request by rmoorman**
This pull request introduces luaJIT version 2.0.4 and 2.0.5 to the installable versions. Furthermore, the luarocks version is updated to 2.4.4.

### CODE REVIEW

**Comment by rmoorman** [comment]
@smashedtoatoms which license should apply? (a missing LICENSE file is the reason for the failing travis build)

**Comment by smashedtoatoms** [comment]
Something not restrictive.  Go ahead and throw and MIT license on there.  Sorry about that.  Thanks for doing this!

**Comment by smashedtoatoms** [comment]
I'm taking care of it.  You'll probably need to rebase yours to pull it in.

**Comment by rmoorman** [comment]
@smashedtoatoms you are welcome and thank you for this plugin 👍

**Pull request merged**
